### PR TITLE
IPBlockIterator bug

### PR DESCRIPTION
**Pull request by samuelwilliams**
The IPBlockIterator never had a unit test created for it and did not seem to work. This PR tests and enhances the IPBlockIterator.

### CODE REVIEW

**Comment by rlanvin** [comment]
Could your be more specific as to what the bug was?

Also in general here, I think this needs some refactoring if you are willing to dig into it. Could getSubblocks return a generator instead of an iterator for instance? That was my original intent (see the comment).

**Comment by samuelwilliams** [comment]
The main problem is that the variable `$current_block` is not instantiated in the constructor so we get the error: 
`Error: Call to a member function plus() on null`

I never picked up on this until I wrote the test for this class.

**Comment by rlanvin** [comment]
Could you cleanup this PR to extract only the relevant commit. Thanks!

**Comment by samuelwilliams** [comment]
Addressed more simply in PR #31

**Pull request closed without merging**
