### PR TITLE
[WIP] Version 3

### PR DESCRIPTION
**Pull request by rlanvin**
I started a branch to support PHP 8.0 and I ended up doing quite a lot of refactoring. I'm using the opportunity to release a v3 for #57 to make some other breaking changes that have been bothering me for some time.

This PR is still a work in progress. I still want to add more tests, in particular when it comes to edge cases and type checking, and improve code coverage before releasing v3. Happy to receive comments.

Changelog/Todos:

- [x] Support for PHP 8.0
- [x] `IPBlock::getMask()` renamed to `IPBlock::getNetmask()`
- [x] `IPBlock::getPrefix()` renamed to `IPBlock::getPrefixLength()`
- [x] `IPBlock::getMaxPrefix()` renamed to `IPBlock::getMaxPrefixLength()`
- [x] `IPBlock::getGivenIpWithPrefixLen()` renamed to `IPBlock::getGivenIpWithPrefixLength()`
- [x] `IPBlock::plus()` and `IpBlock::minus()` now accept numeric strings and GMP instances
- [x] `IPBlockIterator` now implements `ArrayAccess` which means you can write e.g. `IpBlock::create('192.168.0.0/24')->getSubBlocks('/25')[1]`
- [x] `IPBlock::contains` now always throws an `InvalidArgumentException` if mixing IP versions
- [x] Optimise performance of `IP::isPrivate()` by introducing new methods for `IPv4Block`/`IPv6Block`: `getPrivateBlocks()`, `getLoopbackBlock()`, `getLinkLocalBlock()`
- [ ] More tests on the ArrayAccess interface of `IPBlock`
- [ ] Reorganise the methods in `IPBlock` to have a more coherent order and make the class easier to read

### CODE REVIEW

**Comment by timmit-nl** [comment]
Hi rlanvin,

Can I help with any of it? We can't roll out php support for a tool as it hangs on your package ;-)

Tim

**Comment by rlanvin** [comment]
Hey @timmit-nl sorry I haven't been very available lately to finish this PR. Yes of course your help is very welcome. A code review of this PR and maybe even testing it already would be very helpful.

**Comment by timmit-nl** [comment]
We have this for some time now in our dev envoirement and so far we haven't seen any problems. But I will dive into the class to see how we can test better.

**Comment by rlanvin** [comment]
@timmit-nl To facilitate testing I released v3.0.0-rc1 today, and updated the documentation on the wiki. Happy to get some feedback.

**Pull request merged**
